version: '2'

services:

 backup-minio:

  image: rpi-backup-minio
  container_name: backup-minio
  environment:
    CRON_TIME: '* * * * *'
    INIT_BACKUP: 'true'
    MINIO_HOST: minio
    MINIO_HOST_URL: 'http://172.17.0.1:9000'
    MINIO_ACCESS_KEY: 'nibz78'
    MINIO_SECRET_KEY: '?Nitram78250'
    MINIO_BUCKET: 'docker-volume-mysql'
    BACKUP_DIRS: '/backup'
    USE_RESTIC: 'false'
  entrypoint: /bin/sh
  tty: true
  stdin_open: true

  volumes:
          - /backup:/backup
